"""ComfyUI nodes for QDM-trained FLUX.2 Klein RGBA VAEs."""

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .h3_nodes import NODE_CLASS_MAPPINGS as H3_NODES, NODE_DISPLAY_NAME_MAPPINGS as H3_NAMES

NODE_CLASS_MAPPINGS.update(H3_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(H3_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
